name: easy_text_input
description: An easy to use, complete, customisable, non-verbose text input brought to you by Brainn.co
version: 1.0.0
homepage: https://github.com/brainnco/easy_text_input/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: